#!/usr/bin/env bash
# Refresh the @fiscozen/* design-system inventory.
#
# Maintains a sparse, blobless clone of fiscozen/design_system at
# .cache/design_system and writes .claude/design-system-inventory.md so the
# agent can match design regions to existing DS components instead of
# reinventing them.
#
# Run modes:
#   default               — refresh only if .claude/design-system-inventory.md
#                           is older than DS_INVENTORY_TTL_HOURS (24h).
#   DS_INVENTORY_FORCE=1  — force refresh regardless of TTL.
#
# Designed to be invoked from a SessionStart hook (best-effort, non-blocking).
# Network or auth failures leave the existing inventory in place.

set -uo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
CACHE_DIR="$ROOT_DIR/.cache/design_system"
OUTPUT_FILE="$ROOT_DIR/.claude/design-system-inventory.md"
REPO_URL="${DS_REPO_URL:-https://github.com/fiscozen/design_system}"
TTL_HOURS="${DS_INVENTORY_TTL_HOURS:-24}"

log() { printf '[refresh-ds-inventory] %s\n' "$*" >&2; }

# Skip if inventory is fresh and we're not forced. A previous run that hit a
# clone/fetch failure leaves an "inventory unavailable" stub on disk — never
# honour the TTL for that case, otherwise the agent keeps reading the stub
# for the rest of the day.
STUB_MARKER='<!-- inventory unavailable:'
if [ "${DS_INVENTORY_FORCE:-0}" = "0" ] && [ -f "$OUTPUT_FILE" ] \
   && ! head -n 1 "$OUTPUT_FILE" 2>/dev/null | grep -qF "$STUB_MARKER"; then
  if [ "$(uname)" = "Darwin" ]; then
    mtime=$(stat -f %m "$OUTPUT_FILE" 2>/dev/null || echo 0)
  else
    mtime=$(stat -c %Y "$OUTPUT_FILE" 2>/dev/null || echo 0)
  fi
  age_h=$(( ( $(date +%s) - mtime ) / 3600 ))
  if [ "$age_h" -lt "$TTL_HOURS" ]; then
    log "inventory is ${age_h}h old (TTL ${TTL_HOURS}h) — skipping refresh"
    exit 0
  fi
fi

# Required tools
for cmd in git jq; do
  if ! command -v "$cmd" >/dev/null 2>&1; then
    log "missing required command: $cmd"
    exit 0
  fi
done

mkdir -p "$(dirname "$CACHE_DIR")"

# Sparse, blobless clone keeps the cache small (~few MB).
if [ -d "$CACHE_DIR/.git" ]; then
  log "updating cached clone at ${CACHE_DIR#$ROOT_DIR/}"
  if ! git -C "$CACHE_DIR" fetch --depth 1 origin main --quiet 2>/dev/null; then
    log "warn: git fetch failed; keeping existing inventory"
    exit 0
  fi
  git -C "$CACHE_DIR" reset --hard origin/main --quiet
else
  log "creating cached clone (sparse, blobless) at ${CACHE_DIR#$ROOT_DIR/}"
  if ! git clone --depth 1 --filter=blob:none --sparse "$REPO_URL" "$CACHE_DIR" --quiet 2>/dev/null; then
    log "warn: git clone failed; cannot generate inventory"
    if [ ! -f "$OUTPUT_FILE" ]; then
      mkdir -p "$(dirname "$OUTPUT_FILE")"
      cat > "$OUTPUT_FILE" <<EOF
<!-- inventory unavailable: clone of $REPO_URL failed -->
# @fiscozen/* design-system inventory

Inventory generation failed (network or auth). Run \`scripts/refresh-ds-inventory.sh\` manually after fixing the issue.
EOF
    fi
    exit 0
  fi
  git -C "$CACHE_DIR" sparse-checkout set packages >/dev/null 2>&1
fi

SOURCE_SHA=$(git -C "$CACHE_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Render inventory
TMP_FILE=$(mktemp)
{
  echo "<!-- AUTO-GENERATED by scripts/refresh-ds-inventory.sh — do not edit by hand -->"
  echo "<!-- Source: $REPO_URL @ $SOURCE_SHA -->"
  echo
  echo "# @fiscozen/* design-system inventory"
  echo
  echo "Source of truth: [\`fiscozen/design_system\`]($REPO_URL) @ \`$SOURCE_SHA\`."
  echo "Local read-only cache (refreshed at session start): \`.cache/design_system/packages/<name>/\`."
  echo
  echo "## How to use"
  echo
  echo "When implementing a UI region, **match its visual primitive to a package below before writing custom HTML or Tailwind**."
  echo
  echo "**Discover the API.** Read the component source directly to learn props/slots/events:"
  echo
  echo "    .cache/design_system/packages/<name>/src/"
  echo
  echo "**Install on demand.** If you need a component that isn't in the target domain's \`package.json\`:"
  echo
  echo "    pnpm add -F @fz-design/<domain> @fiscozen/<name>@<version>"
  echo
  echo "Use the version from this file. Re-run the script with \`DS_INVENTORY_FORCE=1\` to refresh out of band."
  echo
  echo "## Packages"
  echo
  echo "| Package | Version | Exported components | Description |"
  echo "| --- | --- | --- | --- |"

  for pkg_json in "$CACHE_DIR"/packages/*/package.json; do
    [ -f "$pkg_json" ] || continue
    name=$(jq -r '.name // empty' "$pkg_json")
    case "$name" in @fiscozen/*) ;; *) continue ;; esac
    version=$(jq -r '.version // ""' "$pkg_json")
    desc=$(jq -r '.description // ""' "$pkg_json" | tr '\n|' '  ')
    pkg_dir=$(dirname "$pkg_json")

    # Best-effort: collect exported Fz* component names from src/index.ts
    exports=""
    if [ -f "$pkg_dir/src/index.ts" ]; then
      exports=$(grep -oE 'Fz[A-Z][A-Za-z0-9]*' "$pkg_dir/src/index.ts" 2>/dev/null | sort -u | paste -sd, - | sed 's/,/, /g')
    fi
    [ -z "$exports" ] && exports="—"

    printf '| `%s` | `%s` | %s | %s |\n' "$name" "$version" "$exports" "$desc"
  done | sort

  echo
  echo "## Cross-reference: this hub's installed deps"
  echo
  echo "Per domain — what is currently in \`packages/<domain>/package.json\`:"
  echo
  for pj in "$ROOT_DIR"/packages/*/package.json; do
    [ -f "$pj" ] || continue
    domain=$(jq -r '.name // empty' "$pj")
    case "$domain" in @fz-design/*) ;; *) continue ;; esac
    short=${domain#@fz-design/}
    deps=$(jq -r '(.dependencies // {}) | to_entries | map(select(.key | startswith("@fiscozen/"))) | map("`" + .key + "@" + .value + "`") | join(", ")' "$pj")
    [ -z "$deps" ] && deps="(none)"
    echo "- **$short** (\`$domain\`): $deps"
  done
} > "$TMP_FILE"

mkdir -p "$(dirname "$OUTPUT_FILE")"
mv "$TMP_FILE" "$OUTPUT_FILE"

count=$(grep -cE '^\| `@fiscozen/' "$OUTPUT_FILE" || true)
log "wrote $count packages → ${OUTPUT_FILE#$ROOT_DIR/} (source @ $SOURCE_SHA)"
